plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.80'
}

version = '1.0.0'
group = 'com.frostpunk'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenLocal()
    maven {
        name = "NeoForged"
        url = "https://maven.neoforged.net/releases"
    }
}

dependencies {
    implementation 'net.neoforged:neoforge:21.1.27'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'      : 'FrostpunkMod',
                'Specification-Vendor'     : 'savelijkuhnikov-max',
                'Implementation-Title'     : project.name,
                'Implementation-Version'   : project.jar.archiveVersion,
                'Implementation-Vendor'    : 'savelijkuhnikov-max'
        ])
    }
}